language: csharp
sudo: required
dist: xenial
mono: none
branches:
  only:
  - master
  - dev
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
  - osx
osx_image: xcode10.1
script:
  - curl https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 3.1.103
  - if test "$TRAVIS_OS_NAME" == "linux"; then export PATH="/home/travis/.dotnet":"$PATH"; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then export PATH="/Users/travis/.dotnet":"$PATH"; fi
  - dotnet --info
  - dotnet build -c Release
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet test -c Release ./test/OrchardCoreContrib.Tests/OrchardCoreContrib.Tests.csproj; fi