init:
  - dotnet --version
  - node --version
  - npm --version
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
  - ps: $IsMasterBranch = ($env:APPVEYOR_REPO_BRANCH -eq "master" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)
  - ps: $IsDevBranch = ($env:APPVEYOR_REPO_BRANCH -eq "dev" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)
build_script:
  - dotnet build -c Release
  - ps: if ($IsMasterBranch -or $IsDevBranch) { dotnet pack -c Release --no-build }
init:
  - dotnet --version
  - node --version
  - npm --version
  - git config --global core.autocrlf true

test_script:
  - dotnet test -c Release --no-build .\test\OrchardCoreContrib.Tests\OrchardCoreContrib.Tests.csproj
clone_depth: 1
test: on
deploy: off
image: Visual Studio 2019